# Headless service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "es2-chart.fullname" . }}-es2o{{ .Values.es2o.service.headlessSuffix }}
spec:
  clusterIP: None # Headless service
  ports:
    - port: {{ .Values.es2o.service.port | default 25121 }}
  selector:
    app: {{ include "es2-chart.fullname" . }}
    component: es2o
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "es2-chart.fullname" . }}-es2o
  labels:
    app: {{ include "es2-chart.fullname" . }}
    component: es2o
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.es2o.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ include "es2-chart.fullname" . }}-es2o{{ .Values.es2o.service.headlessSuffix }}
  replicas: {{ .Values.es2o.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "es2-chart.fullname" . }}
      component: es2o
      {{- with .Values.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.es2o.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if and (not .Values.externalSecrets.dbSecret.enabled) (eq (.Values.existingSecrets.dbSecret | default "") "") }}
        checksum/secret-db: {{ include (print $.Template.BasePath "/secret-db.yaml") . | sha256sum }}
        {{- end }}
        {{- if and (not .Values.externalSecrets.storageSecret.enabled) (eq (.Values.existingSecrets.storageSecret | default "") "") }}
        checksum/secret-storage: {{ include (print $.Template.BasePath "/secret-storage.yaml") . | sha256sum }}
        {{- end }}
      labels:
        app: {{ include "es2-chart.fullname" . }}
        component: es2o
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.es2o.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "es2-chart.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default true }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- if .Values.es2o.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.es2o.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.es2o.affinity }}
      affinity:
        {{- toYaml .Values.es2o.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.es2o.tolerations }}
      tolerations:
        {{- toYaml .Values.es2o.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: es2o
          image: "{{ .Values.es2o.image.repository }}:{{ .Values.es2o.image.tag }}"
          imagePullPolicy: {{ .Values.es2o.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.es2o.service.port | default 25121 }}
          envFrom:
            - configMapRef:
                name: {{ include "es2-chart.fullname" . }}-es2o-config
            - secretRef:
                name: {{ include "es2-chart.dbSecretName" . }}
            - secretRef:
                name: {{ include "es2-chart.storageSecretName" . }}
          env:
            - name: ES2O_PORT
              value: {{ .Values.es2o.service.port | default 25121 | quote }}
            - name: ES2O_KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # "es2o-0", "es2o-1", ...
            - name: ES2O_KUBE_SERVICE
              value: {{ include "es2-chart.fullname" . }}-es2o{{ .Values.es2o.service.headlessSuffix }}
            - name: ES2O_LOCK_ID
              value: {{ .Values.es2o.election.lockID | quote }}
          {{- if .Values.es2o.resources }}
          resources:
            {{- toYaml .Values.es2o.resources | nindent 12 }}
          {{- end }}
